[information]
engine = "ollama"

[versions.cpu]
"v0.30.5" = "https://github.com/ggml-org/llama.cpp/releases/download/b9543/llama-b9543-bin-ubuntu-x64.tar.gz"

[versions.vulkan]
"v0.30.5"  = "https://github.com/ggml-org/llama.cpp/releases/download/b9543/llama-b9543-bin-ubuntu-vulkan-x64.tar.gz"

[versions.amd]
"v0.30.5"  = "https://github.com/ggml-org/llama.cpp/releases/download/b9543/llama-b9543-bin-ubuntu-rocm-7.2-x64.tar.gz"

